services:
  db:
    image: mariadb:bionic
    restart: always
    volumes:
      - "rathenadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ragnarok
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok

  login:
    image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
    command: "./login-server"
    restart: always
    ports:
      - "6900:6900"
    volumes:
      - "./conf/import:/rathena/conf/import:ro"
    depends_on:
      db:
        condition: service_started

  char:
    image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
    command: "./char-server"
    restart: always
    ports:
      - "6121:6121"
    volumes:
      - "./conf/import:/rathena/conf/import:ro"
    depends_on:
      db:
        condition: service_started
      login:
        condition: service_started

  map:
    image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
    command: "./map-server"
    restart: always
    ports:
      - "5121:5121"
    volumes:
      - "./conf/import:/rathena/conf/import:ro"
    depends_on:
      db:
        condition: service_started
      char:
        condition: service_started

  web:
    image: "rathena/${mod:-rathena-renewal-vip}:${version:-nightly}"
    command: "./web-server"
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - "./conf/import:/rathena/conf/import:ro"
    depends_on:
      db:
        condition: service_started

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DRIVER: mysql
      ADMINER_SERVER: db
      ADMINER_DB: ragnarok
      ADMINER_PASSWORD: ragnarok
      ADMINER_USERNAME: ragnarok

  panel:
    image: ubermanu/fluxcp
    environment:
      DATABASE_HOST: db
      LOG_DATABASE_HOST: db
      LOGIN_SERVER_HOST: login
      CHAR_SERVER_HOST: char
      MAP_SERVER_HOST: map
    volumes:
      - cplogs:/fluxcp/data/logs
    ports:
      - "80:80"
    depends_on:
      - db
      - login
      - map
      - char

volumes:
  rathenadb:
  cplogs:
