version: "3.6"

services:
  server:
    image: rathena/rathena-renewal
    ports:
      - "6900:6900"
      - "6121:6121"
      - "5121:5121"
    volumes:
      - ./conf:/rathena/conf/import
      - ./mapcache/map_cache.dat:/rathena/db/import/map_cache.dat
    command: ["./athena-start", "watch"]
    depends_on:
      - db

  db:
    image: mariadb
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ragnarok
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  panel:
    image: ubermanu/fluxcp
    environment:
      DATABASE_HOST: db
      LOG_DATABASE_HOST: db
      LOGIN_SERVER_HOST: server
      CHAR_SERVER_HOST: server
      MAP_SERVER_HOST: server
    volumes:
      - cplogs:/fluxcp/data/logs
    ports:
      - "80:80"
    depends_on:
      - db
      - login
      - char
      - map

volumes:
  mariadb:
  cplogs:
